name: Sync bucket

on:
  push:
    branches: [main]
jobs:
  sync-dags:
    name: Sync dags to bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_KEY_JSON }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Sync'
        run: |
          gsutil -m rsync -d  -x "\_\_*."  -r ./dags ${{vars.GCS_DAGS_LOCATION}}